// Export helper functions for RecordingPanel
export function exportAsCode(recording: any, format: 'nano' | 'cypress' | 'puppeteer'): string {
  switch (format) {
    case 'cypress':
      return exportAsCypressTest(recording);
    case 'puppeteer':
      return exportAsPuppeteerScript(recording);
    default:
      return exportAsNanoCode(recording);
  }
}

function exportAsNanoCode(recording: any): string {
  const lines: string[] = [
    '// Generated by Nano Assistant',
    `// Recording: ${recording.name}`,
    `// Created: ${new Date(recording.createdAt).toLocaleString()}`,
    '',
    'import { createAgent } from "./enhanced-agent";',
    '',
    'async function replay() {',
    '  const agent = createAgent();',
    ''
  ];

  for (const action of recording.actions) {
    switch (action.type) {
      case 'navigate':
        lines.push(`  await agent.goto('${action.value}');`);
        break;
      case 'click':
        lines.push(`  await agent.$('${action.selector}').click();`);
        break;
      case 'type':
        lines.push(`  await agent.$('${action.selector}').type('${action.value}');`);
        break;
      case 'scroll':
        lines.push(`  await agent.$('${action.selector}').scrollIntoView();`);
        break;
    }
  }

  lines.push('', '}', '', 'replay();');
  return lines.join('\n');
}

function exportAsCypressTest(recording: any): string {
  const lines: string[] = [
    `describe('${recording.name}', () => {`,
    `  it('should replay recorded actions', () => {`
  ];

  for (const action of recording.actions) {
    switch (action.type) {
      case 'navigate':
        lines.push(`    cy.visit('${action.value}');`);
        break;
      case 'click':
        lines.push(`    cy.get('${action.selector}').click();`);
        break;
      case 'type':
        lines.push(`    cy.get('${action.selector}').type('${action.value}');`);
        break;
    }
  }

  lines.push('  });', '});');
  return lines.join('\n');
}

function exportAsPuppeteerScript(recording: any): string {
  const lines: string[] = [
    "const puppeteer = require('puppeteer');",
    '',
    'async function replay() {',
    '  const browser = await puppeteer.launch();',
    '  const page = await browser.newPage();',
    ''
  ];

  for (const action of recording.actions) {
    switch (action.type) {
      case 'navigate':
        lines.push(`  await page.goto('${action.value}');`);
        break;
      case 'click':
        lines.push(`  await page.click('${action.selector}');`);
        break;
      case 'type':
        lines.push(`  await page.type('${action.selector}', '${action.value}');`);
        break;
    }
  }

  lines.push('', '  await browser.close();', '}', '', 'replay();');
  return lines.join('\n');
}
